version: '3'
services:

    web:
        build: ./
        # During development we map local files into the container
        volumes:
            # Map current working copy into the container
            - ./:/var/www/html/

            # Uncomment to use dev specific PHP settings
            #- ./config/php/local.ini:/etc/php7/conf.d/99-local.ini

            # Uncomment to use the local vendor directory, e.g. for debugging.
            # This requires that you have copied the directory to your host with
            #   docker-compose run --rm web cp -ra /var/www/vendor .
            #- ./vendor:/var/www/vendor
        links:
            - db
        environment:
            # Make sure to tweak this in production
            PHP_FPM_MAX_CHILDREN: 5
            # Enable periodic jobs (see config/crontabs)
            #ENABLE_CROND: 1
        ports:
            - "${DOCKER_LOCAL_PORT}:80"

    db:
        image: mysql:latest
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - ./build/etc/dump/test_db_structure.sql:/docker-entrypoint-initdb.d/a.sql
            - ./build/etc/dump/test_db_data.sql:/docker-entrypoint-initdb.d/b.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
