version: "3"
services:
  web:
    container_name: ${DOCKER_CONTAINER_NAME_WEB}
    build: ./
    # During development we map local files into the container
    volumes:
      # Map current working copy into the container
      - ./:/var/www/html/

      # Uncomment to use dev specific PHP settings
      #- ./config/php/local.ini:/etc/php7/conf.d/99-local.ini

      - ./vendor:/var/www/vendor
    links:
      - db
    environment:
      # Make sure to tweak this in production
      PHP_FPM_MAX_CHILDREN: 5
      # Enable periodic jobs (see config/crontabs)
      #ENABLE_CROND: 1
    ports:
      - "${DOCKER_LOCAL_PORT}:80"

  db:
    container_name: ${DOCKER_CONTAINER_NAME_DB}
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./build/etc/dump/test_db_structure.sql:/docker-entrypoint-initdb.d/a.sql
      - ./build/etc/dump/test_db_data.sql:/docker-entrypoint-initdb.d/b.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    security_opt:
      - seccomp:unconfined
